{{- if .Values.provisioning.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-cve-operator-app.fullname" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "helm-cve-operator-app.labels" . | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  
  template:
    metadata:
      {{- with .Values.provisioning.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-cve-operator-app.labels" . | nindent 8 }}
        {{- with .Values.provisioning.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: "OnFailure"
      imagePullSecrets:
        - name: {{ include "helm-cve-operator-app.fullname" . }}-secrets
      initContainers:
        {{- range .Values.provisioning.initContainers }}
        - name: {{ .name }}
          image: "{{ .repository }}:{{ .tag | default "latest" }}"
          imagePullPolicy: {{ .pullPolicy | default "Always" }}
          command: {{ .command }}
          args: {{ .args }}
          envFrom:
            - configMapRef:
                name: {{ include "helm-cve-operator-app.fullname" $ }}-kafka-configmap
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.provisioning.image.repository }}:{{ .Values.provisioning.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.provisioning.image.pullPolicy | default "Always" }}
          {{- if .Values.provisioning.command }}
          command: {{ .Values.provisioning.command }}
          {{- end }}
          {{- if .Values.provisioning.args }}
          args: {{ .Values.provisioning.args }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "helm-cve-operator-app.fullname" . }}-kafka-secrets
            - configMapRef:
                name: {{ include "helm-cve-operator-app.fullname" . }}-kafka-configmap
          {{- with .Values.provisioning.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
