apiVersion: github.csye7125-su24-team06/v1
kind: GitHubReleasesMonitor
metadata:
  name: {{ include "cve-operator.fullname" . }}-githubreleasesmonitor
  labels:
  {{- include "cve-operator.labels" . | nindent 4 }}
spec:
  owner: {{ .Values.githubReleasesMonitor.owner }}
  repo: {{ .Values.githubReleasesMonitor.repo }}
  monitorFrom: {{ .Values.githubReleasesMonitor.monitorFrom }}
  githubReleaseJobTemplateSpec:
    spec:
      template:
        spec:
          imagePullSecrets: 
          - name: {{ include "cve-operator.fullname" . }}-secrets
          initContainers:
          {{- range .Values.githubreleasemonitor.initContainers }}
          - name: {{ .name }}
            image: "{{ .repository }}:{{ .tag | default "latest" }}"
            imagePullPolicy: {{ .pullPolicy | default "Always" }}
            command: {{ .command }}
            args: {{ .args }}
            envFrom:
              - configMapRef:
                  name: {{ include "cve-operator.fullname" $ }}-kafka-configmap
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.githubreleasemonitor.image.repository }}:{{ .Values.githubreleasemonitor.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.githubreleasemonitor.image.pullPolicy | default "Always" }}
              envFrom:
                - secretRef:
                    name: {{ include "cve-operator.fullname" . }}-kafka-secrets
                - configMapRef:
                    name: {{ include "cve-operator.fullname" . }}-kafka-configmap
              {{- with .Values.githubreleasemonitor.image.resources }}
              resources:
                {{- toYaml . | nindent 12 }}
              {{- end }}
