apiVersion: github.csye7125-su24-team06/v1
kind: GitHubRelease
metadata:
  labels:
    app.kubernetes.io/name: cve-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubrelease-sample
spec:
  id: 166414572
  name: CVE 2024-07-21_1900Z
  tagName: cve_2024-07-21_1900Z
  url: https://api.github.com/repos/CVEProject/cvelistV5/releases/166414572
  createdAt: '2024-07-21T19:05:46Z'
  publishedAt: '2024-07-21T19:06:06Z'
  assets:
    - id: 41898282
      name: 2024-07-21_all_CVEs_at_midnight.zip.zip
      url: https://api.github.com/repos/CVEProject/cvelistV5/releases/assets/180944489
      browserDownloadUrl: https://github.com/CVEProject/cvelistV5/releases/download/cve_2024-07-21_1900Z/2024-07-21_all_CVEs_at_midnight.zip.zip
      createdAt: '2024-07-21T19:06:07Z'
      updatedAt: '2024-07-21T19:06:16Z'
    - id: 180944490
      name: 2024-07-21_delta_CVEs_at_1900Z.zip
      url: https://api.github.com/repos/CVEProject/cvelistV5/releases/assets/180944490
      browserDownloadUrl: https://github.com/CVEProject/cvelistV5/releases/download/cve_2024-07-21_1900Z/2024-07-21_delta_CVEs_at_1900Z.zip
      createdAt: '2024-07-21T19:06:07Z'
      updatedAt: '2024-07-21T19:06:07Z'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: busybox:1.36.1
              imagePullPolicy: Always
              command:
                - 'sh'
                - '-c'
                - 'sleep 60'
