apiVersion: github.csye7125-su24-team06/v1
kind: GitHubReleasesMonitor
metadata:
  labels:
    app.kubernetes.io/name: cve-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubreleasesmonitor-sample
spec:
  owner: "CVEProject"
  repo: "cvelistV5"
  monitorFrom: "now"
  githubReleaseJobTemplateSpec:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: busybox:1.36.1
              imagePullPolicy: Always
              command:
                - 'sh'
                - '-c'
                - 'sleep 60'
          imagePullSecrets: []
