apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-controller-manager
  namespace: '{{ .Release.Namespace }}'
  labels:
    control-plane: controller-manager
  {{- include "helm-cve-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "helm-cve-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "helm-cve-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- if .Values.controllerManager.affinity.enable }}
      affinity:
        {{- include "helm-cve-operator.affinity" . | nindent 8 }}
      {{- end }}

      initContainers:
        {{- range .Values.controllerManager.manager.initContainers }}
        - name: {{ .name }}
          image: "{{ .repository }}:{{ .tag | default "latest" }}"
          imagePullPolicy: {{ .pullPolicy | default "Always" }}
          command: {{ .command }}
          args: {{ .args }}
          envFrom:
          - secretRef:
              name: {{ include "helm-cve-operator.fullname" . }}-kafka-secrets
          - configMapRef:
              name: {{ include "helm-cve-operator.fullname" . }}-kafka-configmap
        {{- end }}

      containers:
      - args: {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.controllerManager.manager.imagePullPolicy }}
        envFrom:
          - secretRef:
              name: {{ include "helm-cve-operator.fullname" . }}-kafka-secrets
          - configMapRef:
              name: {{ include "helm-cve-operator.fullname" . }}-kafka-configmap
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext | nindent 10 }}
      imagePullSecrets:
      - name: {{ include "helm-cve-operator.fullname" . }}-secrets
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "helm-cve-operator.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
