apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-network-policy
  namespace: '{{ .Release.Namespace }}'
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress: {{.Values.networkPolicy.ingress | toYaml | nindent 4}}
  egress: {{.Values.networkPolicy.egress | toYaml | nindent 4}}
