{{- if and .Values.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-pdb
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "helm-cve-operator.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if or .Values.pdb.maxUnavailable (not .Values.pdb.minAvailable) }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
    {{- include "helm-cve-operator.selectorLabels" . | nindent 6 }}
{{- end }}
